### ISSUE TITLE
[2.0.0 REVIEW] A case when both `contentType` and `defaultContentType` are missing

### ISSUE THREAD

**Issue by postatum** [asyncapi/spec#421] opened 2020-08-05 08:10 UTC
Looking at the spec, it's not clear whether `contentType` and `defaultContentType` are required.

These sections' writing makes ones assume the fields are not required, while others assume they are:
* [Message Trait Object](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#messageTraitObject)
* [Message Object](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#message-object)

The issue was brought up in this issue https://github.com/asyncapi/tck/pull/26 and reported because of this comment by @fmvilas: https://github.com/asyncapi/tck/pull/26#issuecomment-669038856

> I think you found a gap in the spec, @postatum. There should be a default value for `defaultContentType` or otherwise make it required (which I don't like). Can you create an issue on asyncapi/asyncapi repo?

**Comment by c-pius** [comment] 2021-09-10 07:11
I also just stumbled over this topic. 

[messageObject](https://www.asyncapi.com/docs/specifications/v2.0.0#messageObject) makes the statement `When omitted, the value MUST be the one specified on the defaultContentType field`

[defaultContentType](https://www.asyncapi.com/docs/specifications/v2.0.0#defaultContentTypeString) makes the statement `This value MUST be used by schema parsers when the contentType property is omitted. In case a message can't be encoded/decoded using this value, schema parsers MUST use their default content type.`

I would actually read it like one of them MUST be present and just in case the value of `defaultContentType` leads to an error when parsing messages, the parser may fallback to its default.

The [streetlights](https://www.asyncapi.com/docs/tutorials/streetlights) example also doesn't seem to have any of them which would be an error according to above reasoning.

**Comment by fmvilas** [comment] 2021-09-14 07:07
Yeah, we should probably have a default `defaultContentType` value so when omitted, it would be `application/json` for instance.

**Comment by fmvilas** [comment] 2021-09-14 07:32
Closing as it's a duplicate of #319

**Closed by fmvilas** 2021-09-14 07:32 UTC
Labels: 🐞 Bug, keep-open
