### ISSUE TITLE
Explain "traits" and their use-cases

### ISSUE THREAD

**Issue by clemensv** [asyncapi/spec#600] opened 2021-08-02 06:53 UTC
The spec jumps into defining traits without clarifying use-cases for them. I can imagine them being a way to enforce some uniformity across metadata for several messages at once, but the spec doesn't say that.

**Comment by Fannon** [comment] 2021-08-16 08:49
We currently have an open PR where we discuss and want to more clearly define the trait behavior. Your feedback on this would be very welcome.

See #532

**Comment by fmvilas** [comment] 2021-09-15 05:58
Closing as it's a duplicate of #532.

**Closed by fmvilas** 2021-09-15 05:58 UTC
Labels: 🐞 Bug
