### ISSUE TITLE
Bug on the Message examples usage in the example documents

### ISSUE THREAD

**Issue by joekickass** [asyncapi/spec#506] opened 2021-03-05 19:59 UTC
**Describe the bug**
Either the Message object _examples_ field does not validate, or I am reading the documentation incorrectly. There are no examples (of the examples field =)) to verify against.

**To Reproduce**
1. Create an AsyncAPI document.
2. Add an _examples_ field in the message according to [messageObject](https://www.asyncapi.com/docs/specifications/2.0.0#messageObject).
3. Try to validate the document doing using the [asyncapi-generator](https://github.com/asyncapi/generator)
  - `ag --force-write -o build simple.yaml @asyncapi/html-template`
4. See error.

**Expected behavior**
The generated HTML documentation of *Account Service*

**Sample document**

Taken from [https://github.com/asyncapi/asyncapi/blob/master/examples/2.0.0/simple.yml](https://github.com/asyncapi/asyncapi/blob/master/examples/2.0.0/simple.yml)

```yaml
asyncapi: 2.0.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
      examples:
        - OneUserSignedUp:
            displayName: MyName
            email: myname@example.com
        - TwoUserSignedUp:
            displayName: YourName
            email: yourname@example.com
```

**Comment by derberg** [comment] 2021-03-08 10:12
@joekickass sorry but we are yet missing the examples validation -> https://github.com/asyncapi/parser-js/issues/99

you can see some valid example here https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#message-object-example

the example you found is wrong, would be awesome if you could open a PR that fixes it 🙏🏼

**Comment by fmvilas** [comment] 2021-03-16 12:18
@joekickass I changed the title of your issue. Hope it still makes sense.

**Comment by joekickass** [comment] 2021-03-16 16:08
@fmvilas - No problems!

@derberg - I'll see if I can find some time to get to know the asyncapi and parser-js projects, and open a PR for it.

But just so that I understand the problem (let me know if I've gotten it wrong):

- The [Message Object](https://www.asyncapi.com/docs/specifications/2.0.0#messageObject) specifies an _examples_ field. That field is a map of [key:example], where each example could be of _any_ type. Worth noting is that each example should _ideally_ conform to the _payload_ field (even validate if that field is expressed as schema, e.g. JSON Schema), but there is nothing in the AsyncAPI specification that dictates this (it would simply be a crappy example if not).
- The _examples_ field of the [Message Object](https://www.asyncapi.com/docs/specifications/2.0.0#messageObject) is not the same as the _examples_ keyword of [JSON Schema](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.5), although they express the same thing. A major difference is that the examples keyword MUST validate against its JSON Schema, but the same does not apply to the _examples_ field (as discussed in previous bullet).
- _payload_ MAY contain the JSON Schema _examples_ keyword, but currently doesn't validate because of https://github.com/asyncapi/parser-js/issues/99.

**Comment by derberg** [comment] 2021-03-22 17:07
@joekickass the problem is that example is invalid and unfortunately spec on the website too. So example has to be fixed by following https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md

**Comment by magicmatatjahu** [comment] 2021-07-26 06:36
Is it issue still valid? We don't support yet the validation of payload/headers examples in the ParserJS, but we changed in the `2.1.0` shape of examples (adding the `name` and `summary` fields). Issue will still be open, because of this problem with ParserJS

**Comment by derberg** [comment] 2021-09-27 13:24
no response to @magicmatatjahu comment so I assume it is not valid anymore

**Closed by derberg** 2021-09-27 13:24 UTC
Labels: 🐞 Bug
