### ISSUE TITLE
Where to put JMS specific headers?

### ISSUE THREAD

**Issue by adamretter** [asyncapi/spec#919] opened 2023-04-03 12:25 UTC
The documentation for version 2.6.0 of the AsyncAPI spec seems to contradict itself regards protocol specific headers for JMS.

It says here: https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageObject

> Schema definition of the application headers. Schema MUST be of type "object". It MUST NOT define the protocol headers.

However, if I follow the documentation through:

1. A [`Message` object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageObject) may have a `traits` property.
2. A [`Message Trait` object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageTraitObject) may have a `bindings` property
3. A [`Message Bindings` object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageBindingsObject) may have a 
`jms` property.
4. The [`JMS Message Binding` object](https://github.com/asyncapi/bindings/blob/master/jms/README.md#message) does **not** permit any properties.

If I cannot put the protocol specific headers in the Message or Message Trait, and if I can't put them in the JMS Message Binding... where can I put them?

**Comment by derberg** [comment] 2023-04-03 12:40
@adamretter in AsyncAPI all protocol-specific semantics are delegated to AsyncAPI bindings. You can also have Message level bindings. The problem is just that nobody yet from `JMS` community took time to contribute what these should be and volunteer to maintain it in future.

there was some enquiry in the past https://github.com/asyncapi/bindings/issues/87 but did not go too far. 

does that help?

**Comment by adamretter** [comment] 2023-04-03 13:39
@derberg That is helpful thanks. So I guess we should put things in the [JMS Message Binding object](https://github.com/asyncapi/bindings/blob/master/jms/README.md#message) of our Async API Schema.

We are not experts in JMS, but we can try and help; would you be happy to receive a PR against https://github.com/asyncapi/bindings/tree/master/jms from us?

**Comment by derberg** [comment] 2023-04-03 14:31
Yes please!!! it is hard to find someone to do first step. You might not be experts but doing first step will enable us to share your PR with rest of the community to drag them in with feedback. Thanks 🙏 

Once you open up a PR we will close this issue. For now leaving it open to have it as reminder

**Comment by adamretter** [comment] 2023-04-03 21:38
Thanks @derberg I have sent a PR for a set of JMS bindings to here - https://github.com/asyncapi/bindings/pull/193

**Closed** 2023-06-26 17:48 UTC
Labels: ❔ Question
